language: generic

sudo: false
dist: trusty

branches:
  only:
  - master

matrix:
  include:
  - name: "Python 3.6 - linux"
    env: PYTHON_VERSION=3.6
    os: linux
  - name: "Python 3.7 - linux"
    env: PYTHON_VERSION=3.7
    os: linux
  - name: "Lint"
    env: PYTHON_VERSION=3.7
    os: linux
    script:
    - black . --diff --check
    
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      OS=Linux ;
  else
      OS=MacOSX ;
  fi ;
  wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$OS-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda;
- export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH";
- conda config --set always_yes yes --set changeps1 no;
- conda env create -f environment.yml
- source ~/miniconda/bin/activate cadquery
# - conda install -c conda-forge -c cadquery cadquery=2 python=$PYTHON_VERSION
- conda install -c conda-forge -c defaults -c cadquery python=$PYTHON_VERSION mypy
- pip install git+https://github.com/CadQuery/OCP-stubs.git

install:
- python setup.py install

script:
- cd tests
- pytest -v --cov

after_success:
- codecov


