name: cadquery
channels:
  - cadquery
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - cadquery::pythonocc-core
  - pyparsing
  - black
  - pytest
  - pytest-cov
  - codecov
  - pip
  - pip:
    - "--editable=."