name: cadquery
channels:
  - cadquery
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - ipython
  - ocp=7.5.1
  - pyparsing>=2.1.9
  - sphinx=3.2.1
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - black=19.10b0
  - codecov
  - pytest
  - pytest-cov
  - ezdxf
  - ipython
  - typing_extensions
  - nptyping
  - scipy
  - nlopt
  - pip
  - pip:
    - "--editable=."
    - sphinxcadquery
